-- Michelle Artistry CMS Schema
-- Run this in the Supabase SQL editor.

-- ============================================================
-- TESTIMONIALS TABLE
-- ============================================================

create table if not exists public.testimonials (
    id bigint generated by default as identity primary key,
    name text not null,
    role text not null,
    text text not null,
    rating integer not null default 5 check (rating >= 1 and rating <= 5),
    avatar_url text,
    visible boolean not null default true,
    created_at timestamptz not null default now()
);

alter table public.testimonials enable row level security;

-- Public can read visible testimonials
do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'testimonials'
          and policyname = 'Public can read testimonials'
    ) then
        create policy "Public can read testimonials"
        on public.testimonials
        for select
        using (visible = true);
    end if;
end $$;

-- Admin write access (same open policy pattern as artworks)
do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'testimonials'
          and policyname = 'Public can insert testimonials'
    ) then
        create policy "Public can insert testimonials"
        on public.testimonials
        for insert
        with check (true);
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'testimonials'
          and policyname = 'Public can update testimonials'
    ) then
        create policy "Public can update testimonials"
        on public.testimonials
        for update
        using (true);
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'testimonials'
          and policyname = 'Public can delete testimonials'
    ) then
        create policy "Public can delete testimonials"
        on public.testimonials
        for delete
        using (true);
    end if;
end $$;

-- ============================================================
-- ARTWORKS TABLE
-- ============================================================

-- Create the portfolio CMS table expected by the admin dashboard and gallery pages.
-- Run this in the Supabase SQL editor.

create table if not exists public.artworks (
    id bigint generated by default as identity primary key,
    title text not null,
    category text not null,
    image_path text not null unique,
    note text,
    description text,
    show_on_homepage boolean not null default false,
    homepage_order integer,
    created_at timestamptz not null default now()
);

-- Migration: add columns to existing table if they don't exist yet
do $$
begin
    if not exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'artworks' and column_name = 'show_on_homepage'
    ) then
        alter table public.artworks add column show_on_homepage boolean not null default false;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'artworks' and column_name = 'homepage_order'
    ) then
        alter table public.artworks add column homepage_order integer;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'artworks' and column_name = 'description'
    ) then
        alter table public.artworks add column description text;
    end if;
end $$;

alter table public.artworks enable row level security;

-- Read access for the public gallery.
do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'artworks'
          and policyname = 'Public can read artworks'
    ) then
        create policy "Public can read artworks"
        on public.artworks
        for select
        using (true);
    end if;
end $$;

-- Temporary open write access for the local admin dashboard.
-- Replace these policies with stricter auth rules before going live.
do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'artworks'
          and policyname = 'Public can insert artworks'
    ) then
        create policy "Public can insert artworks"
        on public.artworks
        for insert
        with check (true);
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'artworks'
          and policyname = 'Public can delete artworks'
    ) then
        create policy "Public can delete artworks"
        on public.artworks
        for delete
        using (true);
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'artworks'
          and policyname = 'Public can update artworks'
    ) then
        create policy "Public can update artworks"
        on public.artworks
        for update
        using (true);
    end if;
end $$;

-- ============================================================
-- HOMEPAGE SPOTLIGHT TABLE
-- ============================================================
-- Stores the up to 3 images that appear on the homepage showcase.
-- These are uploaded separately from portfolio artworks via the
-- "Homepage Spotlight" section in the admin dashboard.
--
-- Storage: create a NEW bucket called "spotlight" in Supabase Storage
-- (Storage > New bucket > Name: spotlight > Public: ON)

create table if not exists public.homepage_spotlight (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    category text not null,
    image_path text not null unique,
    display_order integer not null default 1,
    created_at timestamptz not null default now()
);

alter table public.homepage_spotlight enable row level security;

-- Public read
do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'homepage_spotlight'
          and policyname = 'Public can read homepage_spotlight'
    ) then
        create policy "Public can read homepage_spotlight"
        on public.homepage_spotlight for select using (true);
    end if;
end $$;

-- Admin write (insert)
do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'homepage_spotlight'
          and policyname = 'Public can insert homepage_spotlight'
    ) then
        create policy "Public can insert homepage_spotlight"
        on public.homepage_spotlight for insert with check (true);
    end if;
end $$;

-- Admin write (update — for reordering)
do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'homepage_spotlight'
          and policyname = 'Public can update homepage_spotlight'
    ) then
        create policy "Public can update homepage_spotlight"
        on public.homepage_spotlight for update using (true);
    end if;
end $$;

-- Admin write (delete)
do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'homepage_spotlight'
          and policyname = 'Public can delete homepage_spotlight'
    ) then
        create policy "Public can delete homepage_spotlight"
        on public.homepage_spotlight for delete using (true);
    end if;
end $$;
