-- Create the portfolio CMS table expected by the admin dashboard and gallery pages.
-- Run this in the Supabase SQL editor.

create table if not exists public.artworks (
    id bigint generated by default as identity primary key,
    title text not null,
    category text not null,
    image_path text not null unique,
    note text,
    created_at timestamptz not null default now()
);

alter table public.artworks enable row level security;

-- Read access for the public gallery.
do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'artworks'
          and policyname = 'Public can read artworks'
    ) then
        create policy "Public can read artworks"
        on public.artworks
        for select
        using (true);
    end if;
end $$;

-- Temporary open write access for the local admin dashboard.
-- Replace these policies with stricter auth rules before going live.
do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'artworks'
          and policyname = 'Public can insert artworks'
    ) then
        create policy "Public can insert artworks"
        on public.artworks
        for insert
        with check (true);
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'artworks'
          and policyname = 'Public can delete artworks'
    ) then
        create policy "Public can delete artworks"
        on public.artworks
        for delete
        using (true);
    end if;
end $$;
