-- Michelle Artistry portfolio CMS migration
-- Creates the artworks table, storage bucket, and base policies used by the admin dashboard.

create table if not exists public.artworks (
    id bigint generated by default as identity primary key,
    title text not null,
    category text not null,
    image_path text not null unique,
    note text,
    created_at timestamptz not null default now()
);

alter table public.artworks enable row level security;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'artworks'
          and policyname = 'Public can read artworks'
    ) then
        create policy "Public can read artworks"
        on public.artworks
        for select
        using (true);
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'artworks'
          and policyname = 'Public can insert artworks'
    ) then
        create policy "Public can insert artworks"
        on public.artworks
        for insert
        with check (true);
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'artworks'
          and policyname = 'Public can delete artworks'
    ) then
        create policy "Public can delete artworks"
        on public.artworks
        for delete
        using (true);
    end if;
end $$;

insert into storage.buckets (id, name, public)
values ('artworks', 'artworks', true)
on conflict (id) do nothing;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'storage'
          and tablename = 'objects'
          and policyname = 'Public can read artworks files'
    ) then
        create policy "Public can read artworks files"
        on storage.objects
        for select
        using (bucket_id = 'artworks');
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'storage'
          and tablename = 'objects'
          and policyname = 'Public can upload artworks files'
    ) then
        create policy "Public can upload artworks files"
        on storage.objects
        for insert
        with check (bucket_id = 'artworks');
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'storage'
          and tablename = 'objects'
          and policyname = 'Public can delete artworks files'
    ) then
        create policy "Public can delete artworks files"
        on storage.objects
        for delete
        using (bucket_id = 'artworks');
    end if;
end $$;
